### ISSUE TITLE
Other Proxy Support

### ISSUE THREAD

**Issue by Ancocodet** [TimoCloud/TimoCloud#114]
**What do you have an idea for?**
Support for other Proxies then BungeeCord,
e.g. Velocity or WaterFall.

**Describe your idea**
Give the possibility to use e.g. Velocity as ProxyServer.

**Additional context**
[Velocity](https://velocitypowered.com/)
[Waterfall](https://github.com/PaperMC/Waterfall)

**Comment by TheMagBum** [comment]
We already support the two specified proxies :)
