### ISSUE TITLE
Conole Warning for LuckPerms

### ISSUE THREAD

**Issue by Nandiniae** [TimoCloud/TimoCloud#127]
**Describe the bug**
The Warning `[LuckPerms] Loaded class com.sun.jna.Platform from TimoCloud v6.4.3 which is not a depend, softdepend or loadbefore of this plugin.` apperas on server start

**To Reproduce**
1. Where does it happen? (Server running TimoCloud v6.4.3 and paper 1.16.5 (git-Paper-794))
2. When does it happen? 'On Startup with LuckPerms v5.4.57'
3. Do you know why it happens? (special input data, etc.) 'probably incorrectly shading of the following class `com.sun.jna.Platform`'

**Expected behavior**
No warning to appear in console

**Operating System (please complete the following information):**
 - OS: [Debian]
 - Version [11.6]

**Comment by TheMagBum** [comment]
Hey,

this is not a bug or an error from TimoCloud.
It is just a warning which can be easily ignored as it has no effect on the functioning of TimoCloud.qq
