### ISSUE TITLE
Screen wird gekillt, nach bestimmter Zeit wo keine Reaktion kam

### ISSUE THREAD

**Issue by DerMagsch** [TimoCloud/TimoCloud#54]
**What do you have an idea for?**
Server / Proxy

**Describe your idea**
Wenn der Server aus den server.properties die max-tick-time Sekunden kein bestimmtes Signal sendet, wird die Screen-Session gekillt

**Additional context**
-

**Comment by TheMagBum** [comment]
Hey, I would have now made a watcher that looks every 10 seconds at screen-ls whether the screen still exists. If not, the server is marked as disconnected. This prevents the stuck in the Starting State or so. 

To the off timing, there I will make that if the server 60 seconds no player count has sent (is sent every second) the screen is killed. Or do you have another idea?

**Comment by DerMagsch** [comment]
I think thats good

**Comment by TheMagBum** [comment]
am ende sind wir so verblieben das wir die PID abspeichern, schauen ob diese task noch exestiert wenn nicht wird der server als gestoppt gekennzeichnet und das der core timeout befehl gibt womit die base dann die server killt.
300 Sekunden sollte der Timeout sein und dies soll man in serverGroups.json umstellen können
